[project]
name = "{{ project_name }}"
version = "1.0.0"

[inputs]
{% for input in inputs_config %}
{{ input.identifier }} = "{{ input.placeholder }}"
{% endfor %}

[input_formats]
{% for input in inputs_config %}
{{ input.identifier }}_format = "{{ input.format }}"
{% if input.format == "XLSX" %}
{{ input.identifier }}_sheet_name = "{{ input.sheet_name | default('Sheet1') }}"
{{ input.identifier }}_start_row = {{ input.start_row | default(1) }}
{{ input.identifier }}_start_col = {{ input.start_col | default(1) }}
{% endif %}
{% endfor %}

[outputs]
{% for output in outputs_config %}
{{ output.name }}_format = "{{ output.format }}"
{% endfor %}

{% if num_ui_inputs > 0 %}
[ui]
{% for ui_input in ui_inputs_config %}
{{ ui_input.variable }} = "{{ ui_input.label }}"
{% endfor %}
{% endif %}
